baseURL: "https://floork.dev/"
title: floork
paginate: 5
theme: PaperModX

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 1
    - identifier: posts
      name: posts
      url: /posts/
      weight: 3
    - identifier: search
      name: search
      url: /search/
      weight: 3
    - identifier: tags
      name: tags
      url: /tags/
      weight: 4
    - identifier: archives
      name: archives
      url: /archives/
      weight: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

params:
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Home
  description: "This is my Homepage where I want to share my projects"
  keywords: [Blog, Portfolio, Linux]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images:
    [
      "https://secure.gravatar.com/avatar/a3b3a90533fa19548c4aa9c92325e319?s=800&d=identicon",
    ]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  TocSide: 'right'

  assets:
    # disableFingerprinting: true
    favicon: "/assets/favicons/favicon.ico"
    favicon16x16: "/assets/favicons/favicon-16x16.png"
    favicon32x32: "/assets/favicons/favicon-32x32.png"
    apple_touch_icon: "/assets/favicons/apple-touch-icon.png"
    safari_pinned_tab: "/assets/favicons/safari-pinned-tab.svg"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: floork
    subtitle: "IT-Specialist in training"
    imageUrl: "https://secure.gravatar.com/avatar/a3b3a90533fa19548c4aa9c92325e319?s=800&d=identicon"
    imageWidth: 450
    imageHeight: 450
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  # homeInfoParams:
  #   Title: "PaperModX"
  #   Content: |
  #     Welcome to demo of hugo's theme PaperModX.

  #     - **PaperModX** is a simple but fast and responsive theme with useful feature-set that enhances UX.

  #     - PaperModX is based on theme [PaperMod](https://github.com/adityatelange/hugo-PaperMod).

  #     To get started, please head to the [Docs](docs).

  #     To see examples of different contents, head to [examples tag](tags/example).


  socialIcons:
    - name: stackoverflow
      url: "https://stackoverflow.com/users/14971571/floork"
    - name: github
      url: "https://github.com/floork"
    - name: spotify
      url: "https://open.spotify.com/user/mrosflorian1"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html

  contentDir: /posts/
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  outputs:
    home:
      - HTML
      - RSS
      - JSON # is necessary
